/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jware.solar;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paul Jackson<jjacks55@email.cpcc.edu>
 */
public class ArraySizing extends javax.swing.JFrame {
    private static final long serialVersionUID = 0xFFL;
    
    boolean DEBUG = false;

    /**
     * Creates new form ArraySizingMain
     */
    public ArraySizing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loadTable = new javax.swing.JTable();
        addRowButton = new javax.swing.JButton();
        deleteRowButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalAvgWattsText = new javax.swing.JFormattedTextField();
        totalWattsText = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        dcSysVoltText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        invEffText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dayAutoText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dischargeLimit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ampHrText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        battvoltText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        avgAmpHrDayText = new javax.swing.JFormattedTextField();
        batterParallelText = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        totalBatteriesText = new javax.swing.JFormattedTextField();
        batteriesInSeriesText = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        batteryEfficiencyText = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        peakSunHrsDayText = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        peakAmpsModuleText = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        arrayPeakAmpsText = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        modulesInParallelText = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        modulesInSeriesText = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        totalPanelsText = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        moduleVoltageText = new javax.swing.JTextField();
        recalculateButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Load"));

        loadTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Qty.", "Volts", "Amps", "Watts AC", "Hrs/Day", "Days/Wk", "Total Watts"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        loadTable.setToolTipText("\"Enter the load information as indicated.\"");
        loadTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(loadTable);
        loadTable.getColumnModel().getColumn(0).setResizable(false);
        loadTable.getColumnModel().getColumn(0).setPreferredWidth(170);
        loadTable.getColumnModel().getColumn(1).setResizable(false);
        loadTable.getColumnModel().getColumn(1).setPreferredWidth(50);
        loadTable.getColumnModel().getColumn(2).setResizable(false);
        loadTable.getColumnModel().getColumn(2).setPreferredWidth(50);
        loadTable.getColumnModel().getColumn(3).setResizable(false);
        loadTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        loadTable.getColumnModel().getColumn(4).setResizable(false);
        loadTable.getColumnModel().getColumn(5).setResizable(false);
        loadTable.getColumnModel().getColumn(5).setPreferredWidth(60);
        loadTable.getColumnModel().getColumn(6).setResizable(false);
        loadTable.getColumnModel().getColumn(6).setPreferredWidth(60);
        loadTable.getColumnModel().getColumn(7).setResizable(false);

        addRowButton.setText("Add Load");
        addRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRowButtonActionPerformed(evt);
            }
        });

        deleteRowButton.setText("Delete Load");

        jLabel1.setText("Total Watts AC:");

        jLabel2.setText("Total Average Watts:");

        totalAvgWattsText.setEditable(false);
        totalAvgWattsText.setBackground(new java.awt.Color(204, 204, 204));
        totalAvgWattsText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        totalAvgWattsText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalAvgWattsText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        totalWattsText.setEditable(false);
        totalWattsText.setBackground(new java.awt.Color(204, 204, 204));
        totalWattsText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        totalWattsText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalWattsText.setToolTipText("");
        totalWattsText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addRowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteRowButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(totalWattsText, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalAvgWattsText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(totalAvgWattsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalWattsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addRowButton)
                        .addComponent(deleteRowButton)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Battery Sizing"));

        dcSysVoltText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("DC System Voltage:");

        invEffText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        invEffText.setText("0.9");

        jLabel4.setText(" Inverter Efficiency:");

        dayAutoText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Days of Autonomy:");

        dischargeLimit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dischargeLimit.setText("0.5");

        jLabel6.setText("Discharge Limit:");

        ampHrText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setText("AH Capacity:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel10.setText("Enter The Following Information:");

        battvoltText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setText("Batttery Voltage:");

        jLabel8.setText("Average Amp-Hrs. / Day:");

        jLabel9.setText("Batteries in Parallel:");

        avgAmpHrDayText.setEditable(false);
        avgAmpHrDayText.setBackground(new java.awt.Color(204, 204, 204));
        avgAmpHrDayText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        avgAmpHrDayText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        avgAmpHrDayText.setText("0");
        avgAmpHrDayText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        batterParallelText.setEditable(false);
        batterParallelText.setBackground(new java.awt.Color(204, 204, 204));
        batterParallelText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        batterParallelText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        batterParallelText.setText("0");
        batterParallelText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel17.setText("Batteries in Series:");

        jLabel18.setText("Total Batteries Needed:");

        totalBatteriesText.setEditable(false);
        totalBatteriesText.setBackground(new java.awt.Color(204, 204, 204));
        totalBatteriesText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        totalBatteriesText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalBatteriesText.setText("0");
        totalBatteriesText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        batteriesInSeriesText.setEditable(false);
        batteriesInSeriesText.setBackground(new java.awt.Color(204, 204, 204));
        batteriesInSeriesText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        batteriesInSeriesText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        batteriesInSeriesText.setText("0");
        batteriesInSeriesText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dcSysVoltText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(invEffText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dischargeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dayAutoText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(battvoltText, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ampHrText, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(avgAmpHrDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(batteriesInSeriesText)
                                    .addComponent(batterParallelText, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalBatteriesText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dcSysVoltText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(invEffText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dayAutoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dischargeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ampHrText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(battvoltText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(avgAmpHrDayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batterParallelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(totalBatteriesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(batteriesInSeriesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Array Sizing"));

        batteryEfficiencyText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setText("Battery Efficiency:");

        peakSunHrsDayText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setText("Peak Sun Hrs./Day:");

        peakAmpsModuleText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setText("Peak Amps/Module:");

        arrayPeakAmpsText.setEditable(false);
        arrayPeakAmpsText.setBackground(new java.awt.Color(204, 204, 204));
        arrayPeakAmpsText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        arrayPeakAmpsText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        arrayPeakAmpsText.setText("0");
        arrayPeakAmpsText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        arrayPeakAmpsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrayPeakAmpsTextActionPerformed(evt);
            }
        });

        jLabel15.setText("Peak Array Amps:");

        modulesInParallelText.setEditable(false);
        modulesInParallelText.setBackground(new java.awt.Color(204, 204, 204));
        modulesInParallelText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        modulesInParallelText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        modulesInParallelText.setText("0");
        modulesInParallelText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel16.setText("Modules In  Parallel:");

        jLabel19.setText("Modules In Series:");

        modulesInSeriesText.setEditable(false);
        modulesInSeriesText.setBackground(new java.awt.Color(204, 204, 204));
        modulesInSeriesText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        modulesInSeriesText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        modulesInSeriesText.setText("0");
        modulesInSeriesText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel20.setText("Total Number Of Panels:");

        totalPanelsText.setEditable(false);
        totalPanelsText.setBackground(new java.awt.Color(204, 204, 204));
        totalPanelsText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        totalPanelsText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalPanelsText.setText("0");
        totalPanelsText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel21.setText("Module Voltage:");

        moduleVoltageText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batteryEfficiencyText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peakSunHrsDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peakAmpsModuleText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moduleVoltageText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arrayPeakAmpsText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modulesInSeriesText)
                            .addComponent(modulesInParallelText, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalPanelsText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batteryEfficiencyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(peakSunHrsDayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(peakAmpsModuleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21)
                    .addComponent(moduleVoltageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(modulesInParallelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(arrayPeakAmpsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(totalPanelsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modulesInSeriesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(48, 48, 48))
        );

        recalculateButton.setText("Recalculate");
        recalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recalculateButtonActionPerformed(evt);
            }
        });

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Save Loads");

        jLabel22.setText("Stand Alone Solar Array Sizer BETA 0.1, GNU Public License, Copyright (C) 2013  J.Paul Jackson; This software is Open Source.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(recalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recalculateButton)
                    .addComponent(doneButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_doneButtonActionPerformed

    private void recalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recalculateButtonActionPerformed
        float qty=0,hrsDay,days;
        float volts, amps, wattsAc, totalWatts;
        float runningWatts=0, runningAvgWatts=0;
        
        try {
            for (int row=0; row<loadTable.getModel().getRowCount();row++) {
                    qty = Float.valueOf( (String)loadTable.getValueAt(row, 1)).floatValue();
                    volts= Float.valueOf((String)loadTable.getValueAt(row, 2)).floatValue();
                    amps= Float.valueOf((String)loadTable.getValueAt(row, 3)).floatValue();
                    wattsAc = qty * volts * amps;
                    runningWatts += wattsAc;
                    loadTable.setValueAt(new Float(wattsAc),row, 4);
                    hrsDay = Float.valueOf((String)loadTable.getValueAt(row, 5)).floatValue();
                    days =  Float.valueOf((String)loadTable.getValueAt(row, 6)).floatValue();
                    totalWatts = wattsAc * hrsDay * days / 7;
                    runningAvgWatts += totalWatts;
                    loadTable.setValueAt(new Float(totalWatts),row, 7);
            }
  //          runningWatts = (float)Math.ceil(runningWatts);
  //          runningAvgWatts = (float)Math.ceil(runningAvgWatts);
            
            totalWattsText.setText(String.valueOf(runningWatts));
            totalAvgWattsText.setText(String.valueOf(runningAvgWatts));

            // Battery Sizing Section

            float dcSysVolt=Float.valueOf(dcSysVoltText.getText()).floatValue();
            float invEff=Float.valueOf(invEffText.getText()).floatValue();
            float aAhDay = runningAvgWatts / invEff / dcSysVolt;
            avgAmpHrDayText.setText(String.valueOf(aAhDay));
            avgAmpHrDayText.requestFocusInWindow();
           
            float daysAuto=Float.valueOf(dayAutoText.getText()).floatValue();
            float dischargeLim=Float.valueOf(dischargeLimit.getText()).floatValue();
            float ampHr=Float.valueOf(ampHrText.getText()).floatValue();
        
            float battsInParallel=(aAhDay*daysAuto)/dischargeLim/ampHr;
            
            battsInParallel = (float)Math.ceil(battsInParallel);
            
            batterParallelText.setText(String.valueOf(battsInParallel));
            batterParallelText.requestFocusInWindow();
            
            float batteriesInSeries = dcSysVolt / Float.valueOf(battvoltText.getText()).floatValue();
            
            batteriesInSeries = (float) Math.ceil(batteriesInSeries);
            
            batteriesInSeriesText.setText(String.valueOf(batteriesInSeries));
            totalBatteriesText.setText( String.valueOf( (float)Math.ceil(batteriesInSeries * battsInParallel)));
            
            // Array Sizing Section
            
            float batteryEfficiency=Float.valueOf(batteryEfficiencyText.getText()).floatValue();
            float peakSunHrsDay=Float.valueOf(peakSunHrsDayText.getText()).floatValue();
            float peakAmpsModule=Float.valueOf(peakAmpsModuleText.getText()).floatValue();

            float arrayPeakAmps=aAhDay/batteryEfficiency/peakSunHrsDay;
            float modulesInParallel=arrayPeakAmps/peakAmpsModule;
            
            modulesInParallel=Math.round(modulesInParallel);
            arrayPeakAmpsText.setText(String.valueOf(arrayPeakAmps));
            modulesInParallelText.setText(String.valueOf(modulesInParallel));

            float moduleVoltage = Float.valueOf(moduleVoltageText.getText());
            float modulesInSeries = (float)Math.ceil(dcSysVolt / moduleVoltage);
            
            modulesInSeriesText.setText( String.valueOf(modulesInSeries) );
            
            float totalPanels = (float)Math.ceil(modulesInParallel * modulesInSeries);
            totalPanelsText.setText(String.valueOf(totalPanels));
   
            arrayPeakAmpsText.requestFocusInWindow();
            modulesInParallelText.requestFocusInWindow();
            

        } catch(NumberFormatException exc) {
            JOptionPane.showMessageDialog(this,
                "Make sure that you enter only numbers in the number fields.",
                "Number input error",
                JOptionPane.ERROR_MESSAGE);        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_recalculateButtonActionPerformed

    private void addRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRowButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) loadTable.getModel();
        model.addRow(new Object[]{" ", " ", " "," ","0"," ", " ", " "});
        // TODO add your handling code here:
    }//GEN-LAST:event_addRowButtonActionPerformed

    private void arrayPeakAmpsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrayPeakAmpsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrayPeakAmpsTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                //    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArraySizing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArraySizing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArraySizing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArraySizing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArraySizing().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRowButton;
    private javax.swing.JTextField ampHrText;
    private javax.swing.JFormattedTextField arrayPeakAmpsText;
    private javax.swing.JFormattedTextField avgAmpHrDayText;
    private javax.swing.JFormattedTextField batterParallelText;
    private javax.swing.JFormattedTextField batteriesInSeriesText;
    private javax.swing.JFormattedTextField batteryEfficiencyText;
    private javax.swing.JTextField battvoltText;
    private javax.swing.JTextField dayAutoText;
    private javax.swing.JTextField dcSysVoltText;
    private javax.swing.JButton deleteRowButton;
    private javax.swing.JTextField dischargeLimit;
    private javax.swing.JButton doneButton;
    private javax.swing.JTextField invEffText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable loadTable;
    private javax.swing.JTextField moduleVoltageText;
    private javax.swing.JFormattedTextField modulesInParallelText;
    private javax.swing.JFormattedTextField modulesInSeriesText;
    private javax.swing.JFormattedTextField peakAmpsModuleText;
    private javax.swing.JFormattedTextField peakSunHrsDayText;
    private javax.swing.JButton recalculateButton;
    private javax.swing.JFormattedTextField totalAvgWattsText;
    private javax.swing.JFormattedTextField totalBatteriesText;
    private javax.swing.JFormattedTextField totalPanelsText;
    private javax.swing.JFormattedTextField totalWattsText;
    // End of variables declaration//GEN-END:variables
}
